name: open_weather
description: "Test project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  hive: ^2.2.3
  dio: ^5.4.0
  get_it: ^7.6.4
  hive_flutter: ^1.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  firebase_storage: ^11.5.5
  json_annotation: ^4.8.1
  flutter_gen: ^5.3.2
       

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true



flutter_gen:
  output: lib/gen/
  line_length: 80 

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
